### PR TITLE
fix: improve years ago calculation accuracy

### LINKED ISSUE #89: Age off by one
Some users see their own age wrong.

### PR DESCRIPTION
**Pull request by matortheeternal**
the previous values were not sufficiently accurate, resulting in leap year drift (resulting in things being 5 days off at a duration of 30 years).  this fix gets us a lot closer to perfect accuracy, with the maximum error being a quarter of a day when calculating `yearsAgo`.

image
(calculations performed on June 20, 2023 at ~12:40AM PST)

this may resolve #89 - it will at least resolve part of the age inaccuracy problem, there may be another issue somewhere else in the codebase.

### CODE REVIEW

**Comment by matortheeternal** [comment]
sure, I'll update to match that implementation 👍

**Comment by matortheeternal** [comment]
@kfarwell I have updated the implementation.  Initially I implemented the skip invalid leap day function as well, but I decided to sanity check and see if the JS date implementation did that automatically - and it does.  So there was no need for that code.

I removed my changes to `monthInMilliseconds` and `yearInMilliseconds` because they are now only used for `relativeTime`, where high level of accuracy is not needed and I'd prefer to limit my changes.

**Review by kfarwell — APPROVED** [review]
Verified this is consistent with the Elixir implementation for edge cases around leap days.

**Comment by kfarwell** [comment]
Perfect, thank you!

**Pull request merged**
